language: node_js
node_js: "6"
sudo: required

env:
  global:
    - MONGODB=3.2.13 REPO=caperneoignis/learning_locker_v2
services:
  - redis-server
before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork
  - docker build -t $REPO .
  
install:
  
before_script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";  
  
script:
  #test with defaults
  - docker run -d -e SITE_URL=LL1 --name LL1 -p 80:80 $REPO
  - ./tests/checkURL.sh -u LL1/data/xAPI/about
  - ./tests/checkURL.sh -u LL1/api
  - ./tests/checkURL.sh -u LL1
  #need special call to get travis-ci ip address
  - docker run -d -e SITE_URL=LL2 -e MONGO_URL=$(/sbin/ip route|awk '/default/ { print $3 }') --name LL2 -p 80:80 -p 27017:27017
  - ./tests/checkURL.sh -u LL2/data/xAPI/about
  - ./tests/checkURL.sh -u LL2/api
  - ./tests/checkURL.sh -u LL2
after_success:
  - docker push $REPO;
    
after_script:
  - docker stop LL1 LL2 && docker rm LL1 LL2
  - docker logout
